spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      # ddl-auto: update
      # ddl-auto: create
