server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://localhost:8761/eureka/

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
# hystrix timeout for specific service
# hystrix.command.<serviceName>.execution.isolation.thread.timeoutInMilliseconds: 60000

# test - UPDATE - seems to work
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000
#

zuul:
  ignored-services: '*'
  routes:
    user-movies-catalog-service:
      path: "/user-movies-catalog-service/**"
      serviceId: user-movies-catalog-service
    movie-service:
      path: "/movie-service/**"
      serviceId: movie-service
    rating-service:
      path: "/rating-service/**"
      serviceId: rating-service
