
zuul:
  routes:
    user-movies-catalog-service:
      path: "/api/user-movies-catalog-service/**"
      serviceId: user-movies-catalog-service
    movie-service:
      path: "/api/movie-service/**"
      serviceId: movie-service
    rating-service:
      path: "/api/rating-service/**"
      serviceId: rating-service
    user-service:
      path: "/api/user-service/**"
      serviceId: user-service
    converter-service:
      path: "/api/converter-service/**"
      serviceId: converter-service
    app:
      url: "http://localhost:3000"

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  ServerListRefreshInterval: 5000
  MaxAutoRetries: 5
  MaxAutoRetriesNextServer: 5
  eureka:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 3000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 72000
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
    dashboard:
      proxy-stream-allow-list: "*"

swagger:
  description: Netflix Zuul API Gateway Server for microservices system.
  version: 1.0.0

info:
  app:
    description: Netflix Zuul API Gateway Server for microservices system.
    version: 1.0.0
